### ISSUE TITLE
Alias file

### ISSUE THREAD

**Issue by pablomayobre** [LIKO-12/LIKO-12#100]
It would be great if LIKO had an "alias" file where you can define aliases to common programs. This file would be a Lua file which returns a table containing the alias as key and the actual command as value.

```lua
return {
   dir = 'ls',
   world = 'hello -s"world"',
   complex = function (a1, a2)
       return "something -s".. a1 .." -j".. (a2 + 2)
   end
}
```

The OS would look for an alias here before actually looking into the Programs. If an alias is found and it is a string, then that string is used as command with the original arguments appended. If the value is a function it will be called like any other program, with it's arguments but the return value will be a command to execute.

**Comment by pablomayobre** [comment]
To fundament some more, this is a really common feature in terminal applications, all Unix/POSIX systems support this, and even PowerShell does.

Also it will help to avoid duplicate commands as is the case of `dir/ls` and will help users to automate stuff by using shorter commands.

**Comment by Rami-Sabbagh** [comment]
It's only some rare cases (`dir/ls` & `shutdown/exit` for now), It really doesn't worth it. "K.I.S.S"
