### ISSUE TITLE
Folder command in Android

### ISSUE THREAD

**Issue by Malmik** [LIKO-12/LIKO-12#102]
Okey, 2 Issues one day :)

I enjoy folder command, becouse you can copy your game to pendrive instead of uploading it to pastebin, but this nice function is not working on android! When i type "folder" in terminal, a popup pops up, which let me chose app to open this file. The only avalaible options is pdf reader and internet app, but i have Root Browser and default system file manager that are not showing in popup, so I can't access my games that i make on phone.

**Comment by Rami-Sabbagh** [comment]
Yeah, the folder command doesn't work on Android, I should add a message to it, however, the appdata folder of LIKO-12 is at /sdcard/Android/data/me.ramilego4game.liko12/files/save/liko12/drives/D/

**Comment by Malmik** [comment]
Thanks!

**Comment by Rami-Sabbagh** [comment]
Fixed in PRE_04 2738d389e79eb124ef4bfc9a1ddf57479a43a9f1, Now prints the path to the appdata folder instead of opening the browser.
