### ISSUE TITLE
Cursor blink covers text behind it

### ISSUE THREAD

**Issue by lhsazevedo** [LIKO-12/LIKO-12#104]
Instead of drawing the cursor above the text, as below:
![gif1](https://user-images.githubusercontent.com/7695608/29036078-52be5c5a-7b74-11e7-81f1-364cec80851b.gif)
It would be better to draw it behind and change the color of the text, like this: (Photoshoped)
![gif2](https://user-images.githubusercontent.com/7695608/29036088-5885bc6e-7b74-11e7-9920-366bde515fb0.gif)

I would like to contribute, but before I begin, I want to know if it is accepted and if anyone has suggestions for approaches to this problem considering the way we draw the line at the moment.

**Comment by LoganDark** [comment]
Or the cursor could just switch the fg/bg colors.
