### ISSUE TITLE
Invalid line alignment

### ISSUE THREAD

**Issue by son-link** [LIKO-12/LIKO-12#107]
Hi. I have a problem to set the text alignment. I try all options, include left, but allways show the error **Invalid line alignment**

![screen](https://user-images.githubusercontent.com/208409/29469820-4969cfa2-844a-11e7-8361-d30ea831ab69.png)

the line in cuestios is `print('LEVEL\nCOMPLETE',24,bigFontY, 100, 'left', 1.5,1.5)`

Thanks in advance

**Comment by LoganDark** [comment]
> cuestios

"Question"?

**Comment by Rami-Sabbagh** [comment]
Thanks for telling me about this, what a mistake in my code, it will be fixed in PRE_04 which will be released very soon.
