### ISSUE TITLE
Glyphs which are missing from font are invisible

### ISSUE THREAD

**Issue by technomancy** [LIKO-12/LIKO-12#11]
If you type a backslash, you won't be able to see it, and your game won't run until you find a way to delete it. This can be very confusing.

Glyphs which are missing should render as a square or some "unknown" thing.

**Comment by Rami-Sabbagh** [comment]
I want a mechanic to detect unknown mechanics, specially utf8 one, on android I enjoy a lot of crashes because of pressing utf8 char button in the keyboard, that's annoying..

**Comment by Rami-Sabbagh** [comment]
Fixed in V0.0.2 PRE
