### ISSUE TITLE
Lint with Luacheck

### ISSUE THREAD

**Issue by pablomayobre** [LIKO-12/LIKO-12#111]
It's generally a good idea to have a linter to do static analysis and find possible errors while coding. I have found Luacheck to be really good at this, and it comes with a LÖVE standard (`love`) that can detect all the LÖVE globals.

Luacheck also supports comments to ignore certain stuff for example if you want to add unrecognized globals.

It will also help detect unneeded variables and conflicting names through the whole code base.

I can possibly offer a PR, which will be most likely hard to review (I may need to change several files) if you are up to it, I can help

**Comment by Rami-Sabbagh** [comment]
After switching to Ubuntu I'm now and to install and use Lua check :) , This issue will be fixed soon.
