### ISSUE TITLE
bluetooth keyboard not working on android

### ISSUE THREAD

**Issue by trabitboy** [LIKO-12/LIKO-12#115]
to be determined if it is a limit of the love run time

( using love 2d runtime and a git clone of liko12 in /sdcard/lovegame )

**Comment by trabitboy** [comment]
just tested the latest love runtime from the playstore with a little listing,
I get keyboard events; I wonder what could block in liko12 
(I tested liko12 with the exact same runtime)

on bare love2d:

testflag=0

text="pif"

function love.load()
 rtex=love.graphics.newCanvas(320,200)
end

function love.draw()

 love.graphics.setCanvas(rtex)
 love.graphics.print(text,0,0)
 if testflag==1 then
	love.graphics.print("test flag",20,0)
 end
 love.graphics.setCanvas()
 love.graphics.draw(rtex,0,0,0,4,4)
end

function love.keypressed(k)
		if k=="return" then
			testflag=1
		end
end

**Comment by Rami-Sabbagh** [comment]
Hello @trabitboy, Sorry for the late replay,

By default, Android starts an application with the textinput disabled, And LIKO-12 enables it whenever your touch the screen, but also disables it in some cases like when the sprite editor is open, or running a game that uses the on-screen touch controls.

I did have a simple tweak to block DiskOS from disabling the textinput after enabling it, and to enable the tweak do the following:

- In LIKO-12 on Android type `appdata` to display the path into the appdata folder.
- Use a file explorer (Like ES File Manager) to reach there, you'll find a file named `bconf.lua`.
- Create a folder and name it `BIOS` then copy and paste `bconf.lua` into that folder.
- Open bconf.lua in a texteditor (Like DroidEdit, or ES File Manager one) and set `_EXKB` to `true` in this line: https://github.com/RamiLego4Game/LIKO-12/blob/master/BIOS/bconf.lua#L42
- Reboot LIKO-12 and enjoy.

**Note:** when a new version of LIKO-12 gets release you better remove that `bconf.lua` file from both the `appdata` and `BIOS` folder, reboot LIKO-12 and re-patch the file.

**Another note:**
Sometimes Android sends a keyrelease directly after a key being pressed, this blocks the system from detecting hotkeys, and there's no easy way to fix that in love.

**Comment by trabitboy** [comment]
Hi !
I will try that thank you.
Further testing showed that I have keyboard input when the onscreen keyboard is shown,
but not when I hit "back" to hide it :)
I was about to rip the content of keyboard.lua, and only let the "keypressed" code,
will try your solution first !

**Comment by trabitboy** [comment]
Hi,
I tested and I saw in the code the effect of your flag, but it doesnt fix my issue,
I did a little video to demonstrate
[https://www.dropbox.com/s/kigr5nlb6o32pzu/20171005_175444.mp4?dl=0](url)

I need to touch the screen to have the android popup keyboard, otherwise "physical" keyboard events are not taken into account .
If I press back to make it disappear, as you can see, the keyboard events do not register anymore.

With a simple love2D program that just uses keypressed, I get keyboard input without the popup keyboard !
I guess it is the input of the more sophisticated "textinput" of love that triggers this behavior.

This is probably something to fix in love2d runtime?
At least if we could use LIKO12 in portrait, the keyboard wouldnt hide the work window,
for that we would need a love2D.apk with a different manifest.

**Comment by trabitboy** [comment]
Hi,
I found how to make the physical keyboard workable in Android in this fork:
[https://github.com/trabitboy/LIKO-12](url)

I'd like to make it parameterizable ( tried bconf.lua, but I can not see what is defined here from keyboard.lua )
I would like to remap the escape key to go to something else on android, but I can't find where to do this.
( quite hard to determine what is visible or not reading the codebase, lua beginner )

**Comment by Rami-Sabbagh** [comment]
Hey, For portrait, LIKO-12 is available on the Google Play store, You can check the itch.io page to find the link to google play.

LIKO-12 for android has 2 things patched:

- Portrait Support.
- Libcurl added for the WEB peripheral to work (The pastebin command).

For the bluetooth keyboard, After enabling that flag in bconf.lua, start LIKO-12 and touch the screen, the soft keyboard will be shown, pull the notification bar from the top of your screen, and press the keyboard notification for changing the language, you will find a checkbox named 'Virtual Keyboard' Uncheck it and press ok.

That's how it works for me.

**Comment by trabitboy** [comment]
Hi!
I can't seem to find this option on Samsung, would you have a print screen ?
My solution is incomplete,  space bar doesn't work  anymore!
Ps: when you say hot keys do not work would you mean escape? ;^)

EDIT : triple checked, apparently no visible option to hide kb by default on android 6 with note 4;
I will continue to try the alternate solution.

**Comment by trabitboy** [comment]
Hi,
thanks for your patience, I found the option on my particular phone .

**Comment by Rami-Sabbagh** [comment]
Hey, Oh I forgot about the issue :( , What a busy life...
