### ISSUE TITLE
In the editor, horizontal scrolling is reversed

### ISSUE THREAD

**Issue by LoganDark** [LIKO-12/LIKO-12#118]

**Comment by Rami-Sabbagh** [comment]
Hey, I'm sure that it's not my fault, it's your computer mouse wheel :P

**Comment by LoganDark** [comment]
No it's not. It's probably yours, because scroll works correctly literally everywhere else

**Comment by lhsazevedo** [comment]
This bug does not happen with other users, it's specific to your setup. Without your help we can not reproduce and therefore we can not correct it.
Feel free to open a PR if you identify the problem. I think we can close this for now.

**Comment by Rami-Sabbagh** [comment]
Hey @lhsazevedo, I have talked with @LoganDark, Then I realized he was talking about **HORIZENTAL** scrolling, It's inverted, I didn't have a mouse with 2 wheels to test it, and now I noticed about it 😛

**Comment by Rami-Sabbagh** [comment]
Fixed in 0828360cb494a8c7715a5a61e0b04275ff70dcf5

**Comment by LoganDark** [comment]
@RamiLego4Game The title says "horizontal" ...

**Comment by lhsazevedo** [comment]
Oops, I just realized now too. Thank you @LoganDark, and sorry for the misunderstanding.
