### ISSUE TITLE
Adjustable font?

### ISSUE THREAD

**Issue by technomancy** [LIKO-12/LIKO-12#12]
Sometimes the font can be difficult to read certain lower-case letters.

I wonder if it wouldn't be better to allow a different font to be used for the textual modes (terminal, console, code) which would resize the window temporarily (until switching back to a non-text mode) to allow 43x14 characters for whatever font is selected instead of hard-coding in the heights and widths of the glyphs in the default font.

But maybe this is too divergent from the original vision of pico-8. I think it's important for the games themselves to run at a fixed resolution for simplicity's sake, and so maybe having a different window size for code editing vs sprite editing is just too inconsistent? Interested in your thoughts on the matter.

**Comment by Rami-Sabbagh** [comment]
I may add the font as a spritemap (special editor) but it should have the same size 5*3, I may look at HD res later, for the editor people can edit .lk12..

**Comment by airstruck** [comment]
I think some of the lower-case letters could be made more readable at the same size. I might give it a shot later.

**Comment by Rami-Sabbagh** [comment]
@airstruck That would be great, I tried to make the small font clear, but I did my best..

**Comment by pablomayobre** [comment]
Is 5x4 too much of a scale? There is [this existing pixel font](https://2.bp.blogspot.com/-rR6qF5e_oi8/Vyrzxlc7XDI/AAAAAAAAQ94/VFEbzulPS9c3BEY9PruVKLa3K_wzbV-jwCLcB/s1600/font.png) at this size which look far better and they are just 1 pixel wider. Note that M, m, W, w would need fixing since they are 5x5

**Comment by Rami-Sabbagh** [comment]
Having a font with a less width is better since that will make the screen fit more chars in the same line

**Comment by pablomayobre** [comment]
I wouldn't care if you display four characters and a scrollbar of some sort if I can read those tiny characters though

**Comment by technomancy** [comment]
The new "a" looks a lot better; I think now that I'm more used to it I don't need an adjustable font.

**Comment by Rami-Sabbagh** [comment]
Under the global pressure I will make the font 5x4

**Comment by Rami-Sabbagh** [comment]
@Positive07 Enjoy, I used the font you gave me with little modifications (check WIP branch) (check my twitter for screenshots)

**Comment by fiveseven808** [comment]
Question: Would it be possible for this to use standard bitmap fonts such as bdf or psf? Here's my recommendation for readability (compared to the animated gif examples in the readme):
https://robey.lag.net/2010/01/23/tiny-monospace-font.html
