### ISSUE TITLE
how to access editors on android

### ISSUE THREAD

**Issue by trabitboy** [LIKO-12/LIKO-12#122]
Hi,
the bluetooth keyboard esc key actually quits on android,
I was wondering how to access the editors,
is there a command line to get there ?

**Comment by Rami-Sabbagh** [comment]
Hey, Try to hold a button named 'Fn' when pressing your 'Esc' key.

You can also access the editors by pressing the back button on your phone (Maybe Twice)

**Comment by trabitboy** [comment]
Double back works, thank you :)

**Comment by Rami-Sabbagh** [comment]
No problem 😊

**Comment by epic8009** [comment]
although a console command to access the editors would be cool

**Comment by Rami-Sabbagh** [comment]
And then how would you exit the editors ??

**Comment by epic8009** [comment]
maybe uh there could be like an editor console for editor related stuff and a quit command in there
