### ISSUE TITLE
When syncing/powering on bluetooth keyboard on android, liko12 reboots ( you lose your work )

### ISSUE THREAD

**Issue by trabitboy** [LIKO-12/LIKO-12#123]
start liko 12
go in graphic editor 
doodle
power the bt keyboard synced to your tablet 
>liko 12 reboots

I can work knowing it but my kids lost their stuff
several times already.

**Comment by Rami-Sabbagh** [comment]
Yeah, happens for me too, it's a LÖVE issue ¯\_(ツ)_/¯
