### ISSUE TITLE
Android: DPad touch controls not responsive to tap

### ISSUE THREAD

**Issue by ghost** [LIKO-12/LIKO-12#126]
For some reason the touch controls on the DPad require you to swipe across them rather than just tapping on them to register input. The regular buttons (start A B) work with tap though.

**Comment by Rami-Sabbagh** [comment]
Nice catch, But I fixed this before, maybe I forgot to push or something like that.

**Comment by Rami-Sabbagh** [comment]
Today while working on my sokoban game, I notice how annoying the touch controls are, so I went throw the code, and re-explored that spaghetti, I found that it's missing one line, the dpad check in the touchpressed event, how stupid it was.

Fixed in 868b9b57ad8485bdc9b88100df5ee91efe63a2bb
