### ISSUE TITLE
Android: Rotating device orientation doesn't properly update the viewport in Sprite editor

### ISSUE THREAD

**Issue by ghost** [LIKO-12/LIKO-12#127]
This only seems to happen in the sprite editor. Coding and terminal update correctly when rotated.

Started in portrait and rotated to landscape
![screenshot_2017-12-29-10-07-06](https://user-images.githubusercontent.com/18691792/34444130-c2cc444e-ec80-11e7-8663-a83c9c322c59.png)
rotated back to portrait
![screenshot_2017-12-29-10-07-18](https://user-images.githubusercontent.com/18691792/34444133-c7651b3e-ec80-11e7-8ded-4daf0a7ae982.png)

**Comment by Rami-Sabbagh** [comment]
I have the same issue myself, The LIKO-12 GPU should re-render the screen, (It even does that), but the Android screen rotate animation make that happen, I guess I have to force the GPU to keep redrawing the screen for 1 second on Android when rotating.

**Comment by Rami-Sabbagh** [comment]
Fix this issue in 32935f365ac24f3365cd34f278aba1271ea3209a, Will be out in the next release (V0.6.0_PRE_08)
