### ISSUE TITLE
Feature Request: Sprite Editor- Box Select and Move Selection

### ISSUE THREAD

**Issue by ghost** [LIKO-12/LIKO-12#128]
It would be very helpful to have a basic box selection tool that allows you to move your selection around.

**Comment by XenonLab-Studio** [comment]
Very useful for making simple animations. Exactly like for TIC-80. It would be very useful.

**Comment by Rami-Sabbagh** [comment]
This could be already done by using WASD controls https://liko-12.github.io/#/Documentation/Guides/Keyboard_shortcuts?id=sprites-editor
