### ISSUE TITLE
Feature Request: Android: Code Editor- Scroll Buttons

### ISSUE THREAD

**Issue by ghost** [LIKO-12/LIKO-12#129]
Touch keyboards for Android typically don't have arrow keys making it difficult to navigate a text editor window without scrollbars. I suggest adding little up/down/left/right buttons to the Code Editor UI which emulate arrow key input.

**Comment by Rami-Sabbagh** [comment]
Hey, you can already scroll on the editors by holding two fingers on the screen and moving them.

**Comment by ghost** [comment]
Oh awesome, I had no idea.

**Comment by Rami-Sabbagh** [comment]
So the problem solved, right ? If so then close this issue.
