### ISSUE TITLE
Two-button sprite editing

### ISSUE THREAD

**Issue by airstruck** [LIKO-12/LIKO-12#13]
Feature suggestion: allow use of left and right mouse buttons when editing sprites. Left click on palette selects one color, right click selects another. Left click on sprite editor draws with "left color," right click draws with "right color." This way you can right-click on black and use right mouse button to "erase," for example.

**Comment by Rami-Sabbagh** [comment]
This is a good suggection, I'll added it in v0.0.2

**Comment by Rami-Sabbagh** [comment]
It will be in V0.0.2 for now
