### ISSUE TITLE
Windows7: Uncommon sprite drawing offset

### ISSUE THREAD

**Issue by ghost** [LIKO-12/LIKO-12#132]
Rarely when drawing a sprite the sprite actually drawn is offset by +1 on the y-axis. That is, the coordinate to sample the sprite from on the sprite-sheet is offset, not where it is drawn on screen. It is a consistent error-- that is, it will continuously happen if the drawing conditions are not changed. For example in the screenshot I took below, as long as I did not move my internal camera position on the y-axis, it would continue to draw the sprites offset by 1px from the correct spritesheet coordinates.
![drawing offset bug](https://user-images.githubusercontent.com/18691792/34636293-09ab117e-f253-11e7-92c4-bb957984b47e.png)

Does not seem to happen on android however.

**Comment by pablomayobre** [comment]
Are you rounding your coordinates before hand (either with `math.floor` or `math.ceil`)?

**Comment by ghost** [comment]
That might fix it; will have to give it a shot when I get home. However, it still shouldn't be sampling the sprite from an incorrect coordinate on the sprite sheet regardless if the user gives it float screen coordinates to draw to (which it rounds anyways).

**Comment by Rami-Sabbagh** [comment]
Can you check if it still happens in the latest commit ?

**Comment by Rami-Sabbagh** [comment]
Is this still happening at the latest nightly build ? because I added math.floor to most drawing functions..

**Comment by egordorichev** [comment]
Uh, that's a common graphical issue... Can be solved by using canvases in love2d, flooring the camera position or sprite padding, but that's not doable in your context :X

**Comment by Rami-Sabbagh** [comment]
Does this still happen ?

If it does, try to add `math.floor`

**Comment by ghost** [comment]
I haven't experienced it for a few versions now, I think this can safely be closed
