### ISSUE TITLE
My art at the `snake.lk12` demo

### ISSUE THREAD

**Issue by belen-albeza** [LIKO-12/LIKO-12#133]
Hi, I'm the author of the art that it's currently being used for the `snake.lk12` game that comes with LIKO-12.  See the end of this post in my blog in 2015: https://www.belenalbeza.com/articles/discovering-pico-8/

**This art is being used without my consent and without giving me credit.** So I'm requesting one of these:

a) Remove all of my art from any LIKO-12 games or demos;
or b) Giving me credit properly as a contributor to the games/demos, plus the promise that none of my art will be used again without my prior consent.

Thanks.

PS: If you are in need of graphics, [Kenney](https://kenney.itch.io/) has released a lot of art in the public domain. There's also https://opengameart.org/

**Comment by Rami-Sabbagh** [comment]
Hey, Sorry for this, The snake demo was originally made by someone else for the earlier versions of LIKO-12, and I have re-written the code after the major update.

I didn't know that the art was yours, again, sorry... ~~And I will add your name in the credits.~~ (Edit: Someone drew me new sprites.)

**Comment by belen-albeza** [comment]
Hey, no prob :+1: Thanks for the quick answer and being understanding.

**Comment by Rami-Sabbagh** [comment]
Your art in the snake game has been removed, and replaced with new ones made by gardrek.

---

![liko12-1515851485](https://user-images.githubusercontent.com/6272475/34907681-f98db70e-f88a-11e7-9357-6223359681e8.png)
![liko12-1515851905](https://user-images.githubusercontent.com/6272475/34907716-78ab6112-f88b-11e7-889d-27c0dfce676a.png)

---

![liko12-1515851576](https://user-images.githubusercontent.com/6272475/34907684-fafe0648-f88a-11e7-9bf4-c196d7a74b76.png)
![liko12-1515851932](https://user-images.githubusercontent.com/6272475/34907718-7e350ed0-f88b-11e7-885a-33cf5b46e770.png)

---

(Yes, the new sprites are off-palette :stuck_out_tongue: )
