### ISSUE TITLE
Strange thing about dt global value

### ISSUE THREAD

**Issue by Malmik** [LIKO-12/LIKO-12#137]
Hi. Here it comes:

If you try to do arithmetics or compare "dt" global value in

function _update()

loop, it will work, but if you do this in other function, defined by programmist, lua throws error "attempt to perform arithmetic on global 'dt' (a nil value)"

What is going on? Can you fix it bro?

**Comment by nukeop** [comment]
dt is passed as an argument to _update, it's not global in the scope of your script

**Comment by pablomayobre** [comment]
```lua
function _update (a)
  dt = a

  --Your update code here
end
```
