### ISSUE TITLE
Add screen recording API endpoints

### ISSUE THREAD

**Issue by Eiyeron** [LIKO-12/LIKO-12#139]
Hi.

I'm currently testing Liko-12 from a Pico-8 enthusiast point of view. I'm currently lacking functions to manipulate the internal screen recorder (like P8's `extcmd` commands).
It'd allow me to quickly get my recorder utility working and quickly get looping gifs without post-prod edition.

Thanks in advance and have a nice day.

**Comment by Rami-Sabbagh** [comment]
Implemented in ade6edec84a776980437d693722620e1a921e421
