### ISSUE TITLE
Bug!

### ISSUE THREAD

**Issue by Malmik** [LIKO-12/LIKO-12#141]
If you try to run my code on android (https://pastebin.com/YSfafwee), it crash the app and you need to restart Liko 12.

Compiler do not throws any errors. App just freezes.

**Comment by gardrek** [comment]
This is not a bug. You are running an infinite loop.
If you aren't sure what I am talking about, I suggest looking into learning more about Lua, and programming in general.

**Comment by pablomayobre** [comment]
Yeah there are a few errors:

```lua
random = math.random
```
Means that `random` is a function

```lua
while (random ~= 0) do
```
Means that the loop will evaluate until `random` becomes `0` but random is a function as I said above, and that will never change...

**Comment by Rami-Sabbagh** [comment]
As others said, it's a bug in your code.
