### ISSUE TITLE
Dropping lk12 and disk images

### ISSUE THREAD

**Issue by pablomayobre** [LIKO-12/LIKO-12#152]
Dropping an `.lk12` or disk image (`.png`) on the LIKO-12 window could automatically play the game.

That would really make it easy to play downloaded games in a matter of seconds, which is a really good user experience.

As a note it could be interesting to be able to not only play the game but also edit the file, or save it to the games folder, but that is better decided through discussion and experimenting

**Comment by Rami-Sabbagh** [comment]
Implemented in 13dc30bf28e6e1ba9db277dbca8548b9e887a103
