### ISSUE TITLE
DiskOS Programs exit codes / error throw

### ISSUE THREAD

**Issue by boredom101** [LIKO-12/LIKO-12#155]
Programs should send errors to terminal. Would be useful for conditional chaining.

**Comment by LoganDark** [comment]
Sounds like a great idea for a...

### 🎵 Pull request! 🎵

**Comment by Rami-Sabbagh** [comment]
I've implemented it, it was a good change.
The exit codes are now returned by `term.execute` and `term.executeFile`, with their exit message.

#### The exit codes are:
```
0 -> Success
1 -> Failure
2 -> Execution Error
3 -> Compilation Error
4 -> Command not found 404
```
