### ISSUE TITLE
Lume fails to serialize functions when writing to console

### ISSUE THREAD

**Issue by technomancy** [LIKO-12/LIKO-12#16]
There are two solutions here:
1. Replace `lume.serialize` with [serpent](https://github.com/pkulchenko/serpent) which prints much more nicely but adds an additional dependency.
2. Hack `lume.serialize` to write functions out the same way `tostring` does instead of erroring. I have implemented this before; it is an easy change, but it means our version of lume is essentially a fork.
3. Get it supported in Lume itself: https://github.com/rxi/lume/issues/15 This is ideal but they may not agree.

**Comment by airstruck** [comment]
Do functions actually need to be serialized, or does it just need to not break when it encounters functions?

**Comment by airstruck** [comment]
If it's the latter case, may I recommend [knife/serialize](https://github.com/airstruck/knife/blob/master/knife/serialize.lua), which just ignores stuff it can't serialize (functions, userdata, etc.), is smaller than serpent, features code which is actually readable, and has complete test coverage?

**Comment by airstruck** [comment]
Never mind, just read lume#9.

**Comment by technomancy** [comment]
Yeah, using knife here would probably be better than hacking lume to do what we want.

**Comment by pablomayobre** [comment]
I think what you want is more similar to what [kikito/inspect.lua](https://github.com/kikito/inspect.lua) tries to accomplish. Table serialization for human beings and not for deserialization

**Comment by technomancy** [comment]
I looked at `knife.serialize`, but I think this is not what we want since it omits functions, threads, etc rather than emitting an unreadable representation of them. In this case I believe `inspect.lua` is a better fit.
