### ISSUE TITLE
Case sensitivity on Linux (and probably MacOS/Android?)

### ISSUE THREAD

**Issue by ghost** [LIKO-12/LIKO-12#170]
At startup, right before the prompt there's a line that says:

```
TYPE HELP FOR HELP
```

When I ran Liko-12 for the first time, I typed HELP in upper case, because I wasn't familiar with the case conventions yet. That didn't work, and I then tried the lower case version and that worked. OK, that's not a biggie because it leads you to figure out by yourself.

However, in the case of the help command, the situation is worse. The `Welcome` help file says you can use `help programming`, `help whatsnew` and `help credits`, but neither of these works, because they need to be capitalized: `help Programming`, `help Whatsnew`, `help Credits`. That's more difficult to figure out, and at first it seemed to me like the files were just missing by mistake.

Possible solutions that I can think of:

- Modify Welcome to mention the file names capitalized.
- Rename the files in the Help directory to all lowercase.
- Modify Peripherals/HDD.lua to handle both upper and lower case files in all systems (by reading getDirectoryItems and finding a filename that matches case-insensitively). This would be the ideal solution, making Liko-12 be case-insensitive in all systems. It may need more than that; I haven't looked in detail at e.g. how the command-line commands are loaded. This would also fix the first issue I had.

**Comment by Rami-Sabbagh** [comment]
Hey, sorry for your touble :(, It's my fault, That was because LIKO-12 commands names were case in-sensitive at 0.6.0_PRE_01, and later changed.

Anyway, the terminal now says `Type help for help`, and Corrected the Welcome help file.

**Comment by ghost** [comment]
Thanks for taking care of this! :+1:
