### ISSUE TITLE
Read File

### ISSUE THREAD

**Issue by bojjenclon** [LIKO-12/LIKO-12#188]
Is it possible to read a file from a game? There's JSON parsing support, but it seems the fs global isn't available from a cart, so loading an actual JSON file doesn't seem possible (unless I'm missing something).

**Comment by Rami-Sabbagh** [comment]
The JSON api is intended for game saving

**Comment by Rami-Sabbagh** [comment]
And yeah, DiskOS environment is different than games environment

**Comment by bojjenclon** [comment]
Are there any workarounds for that, or will it simply not be supported? I've been enjoying using LIKO-12 as a means of quickly throwing together ideas, but I'd prefer to have some data about entities remain external so as to not clutter my main code file too much, hence the JSON. I totally understand if you don't intend to support it at all given the nature of the fantasy console, but even if there's a somewhat "hackish" way around it I'd be willing to load files in a less than conventional way.

**Comment by Rami-Sabbagh** [comment]
There's a way, you can use multiple code files,
There's a function called `dofile`, `dofile("D:/mygameScript.lua")`

So place your JSON in a code file:
```lua
JSONDatas["Player 1"] = [[
{}
]]
```

**Comment by bojjenclon** [comment]
Awesome, that should work! Thanks, I'll go ahead and close this.

**Comment by Rami-Sabbagh** [comment]
Thanks for closing it, feel free to use discord so you can have faster answers from me.
