### ISSUE TITLE
Sprite sheet copy/paste

### ISSUE THREAD

**Issue by airstruck** [LIKO-12/LIKO-12#19]
Feature suggestion: allow copy/paste between sprite sheet cells. Will speed up sprite animation workflow.

**Comment by Rami-Sabbagh** [comment]
yeah, I wanted that also, i'll see at Wednesday, What did you got for the demo game ? can you provide a screenshot ?

**Comment by Rami-Sabbagh** [comment]
Ctrl-C and Ctrl-V works now in 0.0.4 PRE, and in 0.0.5 DEV (in the master branch) 5 tools buttons has been added (pencil,fill,copy,paster,delete)
