### ISSUE TITLE
New font and special characters

### ISSUE THREAD

**Issue by XenonLab-Studio** [LIKO-12/LIKO-12#191]
The pixelated font that uses Liko-12 is hardly readable. It would be nice to use a pixelated font at the C-64. Pico-8 uses an uppercase font, and uses the Shift + keys combination to print exclusive special characters. I think it's a good idea, it makes the code editor and the command console more enjoyable.

For the special characters I have already created some symbols, if you like the idea I share my work with the project. Thank you.

**Comment by Rami-Sabbagh** [comment]
LIKO-12's font size has been chosen to fit good amount of text into the screen,
any smaller font will make the text harder to read, and any bigger font will make much less text show on the screen.

Soon custom fonts support will be added, and so you can have the choice to change the default font.

About the special characters, I've already implemented extended ASCII support for the next release, you can view the extra characters here:

![LIKO-12's extended ASCII map](https://github.com/RamiLego4Game/LIKO-12/raw/master/Extra/MISC/CharacterMap.png)
