### ISSUE TITLE
c:/ crashes LIKO-12 completely

### ISSUE THREAD

**Issue by maggintosh** [LIKO-12/LIKO-12#196]
When typing "c:/" in the terminal this error comes up:

> Error
> 
> Engine/coreg.lua:38: /drives/C/terminal.lua:229: Drive 'D:/c' doesn't exists !
> 
> 
> Traceback
> 
> Engine/errhand.lua:45: in function 'handler'
> [C]: in function 'error'
> Engine/coreg.lua:38: in function 'resumeCoroutine'
> /Peripherals/CPU.lua:15: in function 'triggerEvent'
> /Peripherals/Keyboard.lua:23: in function 'f'
> Engine/events.lua:144: in function 'trigger'
> main.lua:81: in function <main.lua:64>
> [C]: in function 'xpcall'

**Comment by CozmoCyke** [comment]
c:/ and C:/ returns also a crash for android version 1.0.0.

[[ Engine Error ]] please report this the developer !

**Comment by ghost** [comment]
@maggintosh What exactly are you trying to achieve? I have also noted this occurrence, and it seems that any command with ':/' at the end will crash the console. (#207)

**Comment by pablomayobre** [comment]
This should be fixed together with #207 and #205 in commit b296dbf that merged #209, feel free to reopen if the error persists
