### ISSUE TITLE
Save format

### ISSUE THREAD

**Issue by technomancy** [LIKO-12/LIKO-12#2]
Pico-8 needs to make up a custom format that uses PNG files because of its curious distribution mechanism.

But LÖVE already has a format for distributing games; the `.love` file.

It seems like it would make more sense to make the `.love` file the format that projects are saved to. It would also make it _much_ easier to allow users to use a text editor or of their own choice or bring in sprites from outside.

**Comment by Rami-Sabbagh** [comment]
pico have it's 1 text file save format (.p8)
and for liko, since png saving is code limiting I'll make it save to pastebin ;) like computercraft "pastebin new test" "pastebin get xxxxxx" "pastebin run xxxxxx"

but for that I'll have to code a simplified http api

**Comment by technomancy** [comment]
OK, I understand. Just thought it was worth considering.
