### ISSUE TITLE
Sprite sheet flip/rotate

### ISSUE THREAD

**Issue by airstruck** [LIKO-12/LIKO-12#20]
Feature request: allow rotating sprite sheet cells 90 degrees, and flipping them vertically or horizontally. Will help with designing map tiles with corners and edges, like in this image: http://www.mapeditor.org/img/screenshot-terrain.png

**Comment by Rami-Sabbagh** [comment]
Alright, drawings for this are now in the editorsheet, only have to implement them

**Comment by technomancy** [comment]
@RamiLego4Game do you want me to hook up my implementation from #30 into the buttons you've added to the editorsheet?

**Comment by Rami-Sabbagh** [comment]
Done  in https://github.com/RamiLego4Game/LIKO-12/commit/71c7aae6f39552528da35bd17ed618df7dfef3d1 :3
