### ISSUE TITLE
LIKO-12 1.0.0 console crashed in the windows version.

### ISSUE THREAD

**Issue by CozmoCyke** [LIKO-12/LIKO-12#202]
**Describe the bug**
The launch

**To Reproduce**
0. Extract all files from "LIKO-12_V1.0.0_Windows.zip" download on Github in a public folder.
1. launch windows command line
2. cd in the liko-12 folder
3.  type "LIKO-12_Console.exe" in the command line of the current directory
4. the app crashed and display the following lines

 D:\portable\liko-12-1.0.0>LIKO-12_Console.exe
Error: BIOS/bconf.lua:11: Init Err: /Peripherals/GPU/modules/window.lua:34: Cann
ot link shader program object:
Fragment shader(s) failed to link,  vertex shader(s) failed to link.
unexpected error.
unexpected error.

stack traceback:
        [string "boot.lua"]:637: in function <[string "boot.lua"]:633>
        [C]: in function 'PA'
        BIOS/bconf.lua:11: in function 'bconfChunk'
        BIOS/init.lua:182: in main chunk
        main.lua:41: in function 'load'
        main.lua:57: in function 'runReset'
        main.lua:65: in function <main.lua:45>
        [C]: in function 'xpcall'
        [string "boot.lua"]:650: in function <[string "boot.lua"]:639>
        [C]: in function 'xpcall'

D:\portable\liko-12-1.0.0>

**Expected behavior**
Launch LIKO-12 console app

**Desktop (please complete the following information):**
 - OS: Windows 7

**Comment by TheSainEyereg** [comment]
![image](https://user-images.githubusercontent.com/37226226/45049194-919ea680-b086-11e8-9c87-27a2a02daafa.png)

I dont know. On my computer its working normal/

- OS: Windows 10 1803

**Comment by CozmoCyke** [comment]
I try also to launch the LIKO-12.exe and it doesn't crash but I have only a window which opens with a blue background but liko-12 is never launched !

**Comment by pablomayobre** [comment]
This sounds like a driver issue, and needs more investigation, the shaders are not linking correctly which means LIKO can't draw anything at all to the screen

**Comment by Rami-Sabbagh** [comment]
Due to the lack of information this issue has to be closed, @CozmoCyke if you are still available and could provide more information please re-open the issue.
