### ISSUE TITLE
Missing editors (sound,sprites) in android version 1.0.0

### ISSUE THREAD

**Issue by CozmoCyke** [LIKO-12/LIKO-12#203]
**Describe the bug**
I see only three button  in the right upper corner of the LIKO-12 console (refresh,save,close)

**To Reproduce**
1. launch LIKO-12 by clicking on the LIKO-12 icon.
2. After the prompt in the LIKO-12 virtual console :
3. d:/>
4. d:/> cd games
5. d:/games/> edit snake.lk12
6. the code source of the game "snake" is appearing in the edit windows.

**Expected behavior**
More buttons in the edit windows like "sound" , "sprite".

**Smartphone (please complete the following information):**
 - Device: Motorola Moto G5
 - OS:  Android 7.0

**Comment by TheSainEyereg** [comment]
You launched the wrong editor to run a full-fledged game editor, you have to click the back button on Android or the Escape button on the computer, and what you opened by typing the "edit" command is actually just a text editor.

**Comment by CozmoCyke** [comment]
Thank you for your explanation :-)
I have tried and it works ! :-)

**Comment by pablomayobre** [comment]
Since this was a misunderstanding I'm closing this, I suggest coming over to Discord for more direct support.

Thanks @TheSainEyereg for clarifying

**Comment by Rami-Sabbagh** [comment]
@Positive07 Please can you look into adding a notice message to the user when he uses `edit` for the first time with a `.lk12` file.
