### ISSUE TITLE
cding into created home directory failed

### ISSUE THREAD

**Issue by ghost** [LIKO-12/LIKO-12#215]
**Describe the bug**
Create a directory and cd into it, and suddenly, oh no! It crashed without a trace...

**To Reproduce**
1. type "ls". There's nothing in the disk! I realize this when an empty line pops up on screen.
2. type "mkdir home" to create a home directory. I also typed ls again, and it said it was there.
3. cd into home with "cd home"
4. Whoopdie doo! There's now a scary blue error on the screen. :D

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Deepin Linux 15.7 (based off of Debian)
 - Browser: Chrome, but I ran an AppImage of the application. (I used Chrome to download the file..!)
 - Version: 12 v1.0.0

**Additional context**
Note that it does run the LOVE compiler AppImage successfully.

Here's the error it gave me from the crash:

[==[ Engine Error ]==]

 - Please report this to the developer !
   Github: http://bit.ly/liko12

Engine/coreg.lua:34: /Drives/C/terminal.lua:549: Folder doesn't exists !

Traceback:
----------

Engine/errhand.lua:52: in function 'handler'
[C]: in function 'error'
Engine/coreg.lua:34: in function 'resumeCoroutine'
/Peripherals/CPU.lua:15: in function 'triggerEvent'
/Peripherals/Keyboard.lua:23: in function </Peripherals/Keyboard.lua:22>
Engine/events.lua:52: in function 'trigger'
main.lua:84: in function <main.lua:67>
[C]: in function 'xpcall'

**Comment by pablomayobre** [comment]
Duplicate of #205 fixed on master by b296dbfe9d500402e22c6c94d23ac1635a1afe3e

PS: New release is coming soon!
