### ISSUE TITLE
The Memory Map should be added to the RAM peripheral page

### ISSUE THREAD

**Issue by OniriCorpe** [LIKO-12/LIKO-12#219]
Hi,

I cannot find the RAM map in the documentation (either in the previous one, for 0.6 version)

Could you help me ?

**Comment by Rami-Sabbagh** [comment]
Oh, It looks like I didn't write it in the documentation, here it is:
```
0x0 -> 0x2FFF - The Video RAM
0x3000 -> 0x5FFF - The Label Image
0x6000 -> 0x15FFF - The FDD RAM
```
> **Note:** The FDD RAM is used by DiskOS when saving your game into a `.png`.

**Comment by Rami-Sabbagh** [comment]
@boredom101 Could you add the memory map to the RAM peripheral page ?
https://liko-12.github.io/#/Documentation/Peripherals/RAM/

You'll have to edit the generate.lua script and add support for long peripherals descriptions (like in methods)

**Comment by boredom101** [comment]
I believe I finished.

**Comment by Rami-Sabbagh** [comment]
Thanks @boredom101 !

I made some changes to the long description, please just regenerate the docs then close this issue.
