### ISSUE TITLE
How to use sound effects ?

### ISSUE THREAD

**Issue by OniriCorpe** [LIKO-12/LIKO-12#220]
Hi,

I cannot find the sound effects functions (API) in the documentation.

Is it missing or you've just add the soud effects editor without the users functions ?

Thanks !

**Comment by Rami-Sabbagh** [comment]
For now there are only 2 simple functions:
* `SFX(slotnum, chn)`
**slotnum** is the number of the sfx to play.
**chn** is the number of channel to play the sfx in (0,1,2,3).

* `Audio.stop()`
Stops all the playing sounds.

Check the updated `bounce` demo in LIKO-12 v1.0.0

There is also an advanced api, but it's not stable and will be changed in future versions.
