### ISSUE TITLE
Changing Directory Crashes Engine

### ISSUE THREAD

**Issue by stetro** [LIKO-12/LIKO-12#222]
**Describe the bug**
Its my first try with LIKO-12

**To Reproduce**
I entered following commands
1. `mkdir test`
2. `cd test`

**Screenshots**
![image](https://user-images.githubusercontent.com/805263/50587882-54a5bd80-0e88-11e9-966e-59a0e18f7729.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Löve 11.2
 - Latest liko12 Universal.love

**Comment by pablomayobre** [comment]
Closed this has been fixed #215 #205 #196 #207

In PR #209 commit b296dbfe9d500402e22c6c94d23ac1635a1afe3e
