### ISSUE TITLE
Folder command not working

### ISSUE THREAD

**Issue by paperbenni** [LIKO-12/LIKO-12#223]
**Describe the bug**
the folder command doesn't work. As far as I know it should open the current directory in the host file explorer. For me it does nothing. No output or error ( inside LIKO-12)
When I run LIKO from terminal it puts this in stderr:

`
gio: file:///home/benjamin/.local/share/love/LIKO-12/drives/D/: Error when getting information for file “/home/benjamin/.local/share/love/LIKO-12/drives/D”: No such file or directory
`

The directory does exist and it is not owned by root or anything like that. The issue occurs both with the love and the appimage version, I tried stable and nightly. My PC is running Ubuntu MATE 18.10. I'm using Caja, but I've also tried PcManFM, both work fine, but don't open up from LIKO-12. LIKO is able to open up Firefox though, if that information has any use. 

**To Reproduce**
1. Start up LIKO-12 (from terminal if you want to see any sign of error)
2. type folder
3. Nothing happens
4. LIKO complains in terminal

**Expected behavior**
The default host file explorer should open

**Comment by XenonLab-Studio** [comment]
I confirm the bug. When I create a "mkdir myprojects" folder and try to insert "cd myprojects", it displays the following screen:

![](http://oi68.tinypic.com/jqt1qx.jpg)

**Comment by Rami-Sabbagh** [comment]
I could see, this also happens at my ubuntu installation, I think it's because of a missing ending "/"

The `appdata` command works fine, that's may be why...
