### ISSUE TITLE
Code editor and keywords improvements.

### ISSUE THREAD

**Issue by XenonLab-Studio** [LIKO-12/LIKO-12#228]
**Is your feature request related to a problem? Please describe.**

Liko-12 is fantastic but after using it for a long time I think it's a good idea to make small changes in the code editor.

I refer above all to the keywords!

a small example:

clear() changed to cls()

this facilitates the passage for all users who want to use Liko-12 as an alternative to Pico-8.

In addition to this, I noticed that Liko-12 also has the syntax highlight for call-back functions: I really like this! but I think it is better to adopt a case-insensitive system (font all uppercase) because some keys must be entered with the first capital letter and the editor does not have the intellisense, so it facilitates errors (especially for beginners). The all uppercase system certainly facilitates the reading of the code (the pixelated font in low-case mode makes reading difficult sometimes).

**Describe the solution you'd like.**

I don't think it's difficult to change the keywords' names right? so it's a simple change (I refer only to keywords like: cls (instead of clear), spr (instead of Sprite), and others possible and compatible with Pico-8).

For the font all uppercase there is already a detection system for typing letters in Liko-8 right? I want to check the code, eventually send some commits when I've tested everything and I'm sure of my job.

Thanks for your attention.

Small note: Liko-12 is very beautiful! I love the simplicity and "retro" style of the pure 80s of Pico-8, so please keep this project simple, clean without adding unnecessary languages and things that ruin its old-style nature.

**Thanks Rami Sabbagh ^__-**

**Comment by Rami-Sabbagh** [comment]
Thanks for your positive feedback in the issue report :)

About the problems:
- **Changing the keywords (api functions names):** That's a very hard thing indeed, by changing an API function name, compatibility will be broken with any existing games using that function, It will force me to introduce GameAPI_v3, That's too early for it.
And the plans are to rename the existing (3 characters) functions to proper names instead, I think I'll rename many functions, but all of them should be done for once and then not change again.
You could instead define alternative names according to your needs:
```lua
--At the top lines of your game code:
--API Alternative Names--
cls = clear
ply = polygon
spr = sprite
```

- **Removing small letters support:** Oh no, please no, I've reached my naming freedom by adding small and capital letters support, the font is not that bad, custom fonts support was under work, so once I finish it, you could switch to the "Reversed captilization" font, then use some tricks/hacks to make all the API functions have small letters (which will be displayed as capital)
```lua
--Somthing like this:
for k,v in pairs(_G) do
  _G[string.lower(k)] = v
end
```

**You're welcome Xenon-Studio** :wink:

**Comment by XenonLab-Studio** [comment]
Thanks a lot! you have been of a unique kindness!

By reflecting better on what you wrote, and on the code I read, you're right! I really think I will do the revision to my guide for LIKO-12 where I describe the substantial differences between PICO-8 and LIKO-12, definitely the best choice. I don't want to make the project more complicated, the simplicity of LIKO-12 is what I love.

The case-sensitive I like, PICO-8 uses the upper-case font and with SHIFT you can use very nice and useful special characters that give a retro style (like the C-64) I said this because the special characters would make LIKO- 12 even more interesting.

Thank you very much. I have been following LIKO-12 with interest since it was first published, so if you need donations, and more, just ask, I'll be happy to do my best.

Thanks again ;)

**Comment by Rami-Sabbagh** [comment]
Hey, I've added extended ASCII support in the latest release !

They are custom drawing characters that you could check by typing `charmap` in the terminal.

Then you could write them in the code like this:
```lua
print("\xF0") --Change F0 to the character id you want.
```

**Comment by XenonLab-Studio** [comment]
Very interesting! Thanks for the information, this features is very welcome.

I am also happy that the project is not abandoned, I was afraid it was until 2 months ago. Thank you.

**Comment by Rami-Sabbagh** [comment]
Just wait for me to finish school (About 3 months from now), And tons of commits will happen :wink:

**Comment by XenonLab-Studio** [comment]
I have total confidence in your project and your skills. Thank you very much, Liko-12 is a masterpiece indeed!

I wish you much success with your exams, and when you come back here I will always be willing to support you.
