### ISSUE TITLE
App is not starting

### ISSUE THREAD

**Issue by BaRRaKudaRain** [LIKO-12/LIKO-12#229]
**Describe the bug**
App is not opening on Windows 10

**To Reproduce**
1. Double click the executable file
2. See it crashes

**Expected behavior**
App is up and running

**Desktop (please complete the following information):**
 - OS: Windows 10 1809
 - Browser Microsoft Edge

**Comment by XenonLab-Studio** [comment]
version .love or compiled? to me the .love works! while the compiled version no!

**Comment by BaRRaKudaRain** [comment]
Is it needs to be compiled? I thought that .love is some sort of additional files needed to correct work of the app as dependency. So, if it need to be compiled, how to do it?

**Comment by BaRRaKudaRain** [comment]
I have the compiled version. How to use the love version?

**Comment by XenonLab-Studio** [comment]
@BaRRaKudaRain is simple. If you use .love archives double click on the archive (if you use Windows). or unzip the .love file and use an ide (ZeroBrane Studio advice which is open source and also has the pre-configuration for love2d and the run system).

The compiled version of Liko-12 does not work, I tested it on both Windows and Linux systems.

I hope I was helpful ;)

**Comment by pablomayobre** [comment]
Which version of LIKO-12? Where did you download it from?

**Comment by BaRRaKudaRain** [comment]
@XenonLab-Studio Thank you very much!

**Comment by pablomayobre** [comment]
That doesn't solve the issue though, I'll reopen and reask

Which version of LIKO-12? Where did you download it from?

**Comment by XenonLab-Studio** [comment]
@Positive07 Last stable version. The compiled release does not start. But in addition to this it has critical bugs that will be solved as soon as possible so it doesn't bother me at all. The .love version is easy to use and does not cause problems when starting up.

**Comment by pablomayobre** [comment]
So 1.0.0? Downloaded from here or itch.io?

**Comment by Rami-Sabbagh** [comment]
Moved into #254
