### ISSUE TITLE
I was just messing around for my first time

### ISSUE THREAD

**Issue by kadeska** [LIKO-12/LIKO-12#236]
**Crash Type**
Is it LIKO-12's blue screen of death, red error messags, app crash or a whole device crash ?

Just went to a blue screen with error on screen

**To Reproduce**
1. Type '...'
2. Press '...'
3. Click on '....'
4. Scroll down to '....'
5. See error

**Desktop (please complete the following information):**
 - OS: Windows10
 - Architecture: x64
 - LIKO-12 Version: [e.g. v1.0.0, Nightly 30/12/2019]
 - Downloaded from: github releases
 - Executable type: Windows .exe

**Smartphone (please complete the following information):**
 - Device: [e.g. Samasung J700H]
 - OS: [e.g. Android Oreo, Android 7.0]
 - LIKO-12 Version [e.g. v1.0.0, Nightly 30/12/2019]
 - Downloaded from: [e.g. Play Store, itch.io, github releases]

**Screenshots**

**Crash logs/reports**
```
Paste the crash log/report here:
[==[ Engine Error ]==]

 - Please report this to the developer !
   Github: http://bit.ly/liko12

Engine/coreg.lua:34: not enough memory


Traceback:
----------

Engine/errhand.lua:52: in function 'handler'
[C]: in function 'error'
Engine/coreg.lua:34: in function 'resumeCoroutine'
/Peripherals/CPU.lua:15: in function 'triggerEvent'
/Peripherals/GPU/modules/mouse.lua:38: in function </Peripherals/GPU/modules/mouse.lua:35>
Engine/events.lua:52: in function 'trigger'
main.lua:84: in function <main.lua:67>
[C]: in function 'xpcall'

```

**Additional context**
Cant say what I was doing to reproduce this., I honestly was messing around just exploring and clicking on things and then this happens .

**Comment by Rami-Sabbagh** [comment]
The crash log doesn't give any enough data about the problem,
It's just a "not enough memory (RAM)" crash.

I have to know what you did to make that happen, so maybe I could minimize it's memory usage.

**Comment by Rami-Sabbagh** [comment]
This issue has been closed due to lack of information, @kadeska if you are still available and could provide more information on this issue, please re-open it and do so.
