### ISSUE TITLE
Wrong link in the docs

### ISSUE THREAD

**Issue by Gapstare** [LIKO-12/LIKO-12#260]
Hi!

In the documentation on the top of this page:
https://liko-12.github.io/#/./Documentation/Guides/getting_started

There is a link to the installation instructions that goes to:
https://liko-12.github.io/#/installation
This gives a 404. I'm guessing it should link to this page instead:
https://liko-12.github.io/#/./Documentation/Guides/installation

**Comment by Rami-Sabbagh** [comment]
Fixed it, thanks!
