### ISSUE TITLE
Entering D:\Demos\D causing liko-12 to crash

### ISSUE THREAD

**Issue by aleksejtalanov538** [LIKO-12/LIKO-12#269]
**Crash Type**
blue screen of death

**To Reproduce**
1. Type D:\Demos\D
2. Press Enter
5. See error

**Smartphone (please complete the following information):**
 - Device: Alcatel Onetouch Pixi 3 (10) 3G 9010X
 - OS: Android 5.1
 - LIKO-12 Version v1.0.1
 - Downloaded from: github releases

**Crash logs/reports**
```
[==[ Engine Error ]==]

 - Please report this to the developer !
   Github: http://bit.ly/liko12

Engine/coreg.lua:34: /Drives/C/terminal.lua:235: Drive 'D:/D' doesn't exists !


Traceback:
----------

Engine/errhand.lua:52: in function 'handler'
[C]: in function 'error'
Engine/coreg.lua:34: in function 'resumeCoroutine'
/Peripherals/CPU.lua:15: in function 'triggerEvent'
/Peripherals/Keyboard.lua:32: in function </Peripherals/Keyboard.lua:24>
Engine/events.lua:52: in function 'trigger'
main.lua:84: in function <main.lua:67>
[C]: in function 'xpcall'


```

**Additional context**
This issue producing to all peoples on all devices on all latest versions

**Comment by ha6000** [comment]
Correct me if I am wrong, but I believe android is not being supported anymore, unless this recently changed.

**Comment by IsometricShahil** [comment]
The project is being re-developed in java and libGDX and I am half sure it will support mobile devices. (See branch 2.0.0)
Also maybe a duplicate of [issue 265](https://github.com/LIKO-12/LIKO-12/issues/265).
