### ISSUE TITLE
How do I write my own OS for LIKO-12?

### ISSUE THREAD

**Issue by Rainb0wSkeppy** [LIKO-12/LIKO-12#271]
can you help me i tried to make my own OS for liko12 and i got this error
![image](https://user-images.githubusercontent.com/48686725/125285896-d3b2c100-e323-11eb-8eb2-06d7ac2870ad.png)

boot.lua:
```
--The handled APIS
Handled = ...

--Make peripherals as global
for k,v in pairs(Handled) do
  _G[k] = v
end

CPU.sleep(1)

GPU.color(12)
GPU.print("Custom OS Test")

CPU.sleep(1)
--CPU.restart()
```
can anyone help me

**Comment by Kyllingene** [comment]
Now I'm no expert at programming, even less so with LIKO-12; but it would appear that you stopped something that wasn't supposed to be stopped.

**Comment by Rainb0wSkeppy** [comment]
i figured out how to make a infinite loop without crashing:
```
while true do
    -- Your code here
    CPU.sleep(0.01)
end
```
