### ISSUE TITLE
Drop HTTP communication

### ISSUE THREAD

**Issue by Rami-Sabbagh** [LIKO-12/LIKO-12#279]
Unfortunately the current state of LIKO-12 has issues with connecting to the internet.
And this issue won't be solved soon. So it's better to drop the whole internet connectivity support and let the project develop further without that until the situation helps.

## Factors preventing web access

- The dying Lua ecosystem.
- Most of internet services are forcing HTTPS.
- No workforce available to extend the LÖVE framework and add proper HTTPS support.

**Comment by IsometricShahil** [comment]
HTTPS support has almost landed into LÖVE. The next major release of LÖVE (12.0) will come with built-in HTTPS support through [lua-https](https://github.com/love2d/lua-https) and it's already avaliable in the [12.0 branch](https://github.com/love2d/love/tree/12.0-development/). If upgrading Liko-12 to use LÖVE 12.0 is infeasible then I think lua-https can be integrated into the version of LÖVE used by it.

**Comment by Rami-Sabbagh** [comment]
I think upgrading LIKO-12 to LÖVE 12.0 would be more feasible than back-porting lua-https.

> HTTPS support has almost landed into LÖVE.

This is nice news!

Even though all web code better be wiped from LIKO-12 because it has many issues.

**Comment by Rami-Sabbagh** [comment]
Solved in e074d59fc860a79cad689468913a659c9c6ec58f, 2ca099f033f6a4f18864a5f66e1b688b9dde0e98 and e3649b6e9a223d52a3aab7174419ce8c2b7dd68c
