### ISSUE TITLE
Getting rid of globals

### ISSUE THREAD

**Issue by technomancy** [LIKO-12/LIKO-12#3]
It's rather difficult to follow some of the functionality in the codebase due to the heavy usage of globals.

Cleaning up things to use modules would make it much easier to follow. I may be able to submit a patch for this if you are interested. I have had good luck using luacheck to find globals: https://github.com/mpeterv/luacheck

**Comment by technomancy** [comment]
The problem here is that it would be very likely to conflict with other edits, so maybe we should coordinate about which files to do bef

**Comment by technomancy** [comment]
The problem here is that it would be very likely to conflict with other edits, so maybe we should coordinate about which files to do before beginning.

**Comment by Rami-Sabbagh** [comment]
Fixed in 3c219651dbc72e3b347a38af076047411055c7ff , Carts still have the api as globals (to save code length)
