### ISSUE TITLE
Allow metadata to be stored on carts

### ISSUE THREAD

**Issue by technomancy** [LIKO-12/LIKO-12#33]
It would be useful to have a free-form table where arbitrary metadata can be stored about a cart. They could be used to contain author info, a URL, or license.

Perhaps we could add terminal commands to set and read metadata values, or they could be used by user-level config. One other use case (I'm not sure if this should be merged but it is an interesting idea) is allowing carts to contain code in other languages like I do here: https://github.com/technomancy/LIKO-12/tree/lisp

I can implement this if we can agree on how it should look.

**Comment by Rami-Sabbagh** [comment]
After doing the LIKO-12 RAM section, I gave 1kb for metadata with fields for author and project name.
