### ISSUE TITLE
Undo support

### ISSUE THREAD

**Issue by technomancy** [LIKO-12/LIKO-12#35]
As long as each editor mode supports `export` and `load` I think it should be easy to implement undo once in `editor/init.lua` and have it work for every editor mode.

**Comment by technomancy** [comment]
I would suggest that this should be included in v0.0.5.

**Comment by jminor** [comment]
Partially addressed by #116

**Comment by Rami-Sabbagh** [comment]
Thanks for @jminor for addressing this issue
