### ISSUE TITLE
Allow setting flag bits in sprite editor

### ISSUE THREAD

**Issue by technomancy** [LIKO-12/LIKO-12#37]
Plus an API for reading them.

**Comment by cosme12** [comment]
What are these flags used for?

**Comment by Rami-Sabbagh** [comment]
Those can be good when people make some game engines, so you can for ex tell them which sides to enable collision on, is it a deadly tile ?, should draw this tile ?

**Comment by technomancy** [comment]
I wonder if this makes sense for the 0.0.5 milestone; it seems like a more advanced feature than the other issues that we have selected for 0.0.5.

**Comment by Rami-Sabbagh** [comment]
Muhahahaha finished this in v0.6, it was fun to do

**Comment by Rami-Sabbagh** [comment]
Muhahahaha finished this in v0.6, it was fun to do
