### ISSUE TITLE
Problem when uses mouse scroll on code editor

### ISSUE THREAD

**Issue by DrZanuff** [LIKO-12/LIKO-12#55]
In versrion v.0.0.4 PRE, in the code editor, whenever i use the scroll wheel, up or down, the application throws me an Error in a blue screen:

> Error
> 
> editor/code.lua:79: attempt to call method '_kpress'(a nil value)
> 
> Traceback
> 
> editor/code.lua:79: in function '_nmove'
> editor/init.lua:61: in function '_mmove'
> autorun.lua:40 in function '_auto_mmove'
> main.lua:25: in functionmain.lua:24
> main.lua:172: in functionmain.lua:148
> [C]: in function 'xpcall'

**Comment by cosme12** [comment]
If I'm not wrong, this got fixed in the next version. At least, it's working for the v.0.0.5 DEV

**Comment by Rami-Sabbagh** [comment]
It's fixed in 0.0.5 DEV, Which will be out this friday as PRE
