### ISSUE TITLE
LIKO-12 saves to ~/.local/share/love/.liko12

### ISSUE THREAD

**Issue by josefnpat** [LIKO-12/LIKO-12#57]
There are two issues with the current save location (`~/.local/share/love/.liko12`)

1) It starts with a `.` which hides the folder on unix systems
2) It is in the love subdirectory, which would imply that it's a love application, instead of it's own application.

You can fix 1) this by changing `t.identity = ".liko12"` to `t.identity = "liko12"`

You used to be able to fix 2) by marking `t.release` as true. I'm not sure what you have to do to change that now, or if you can.

**Comment by Rami-Sabbagh** [comment]
Hmm, I'll have to change the directory in V0.0.5 before more users come to use..

**Comment by Rami-Sabbagh** [comment]
Fixed in af32686277aa393d6bbfd4fbd7a0030cc15c085e

**Comment by josefnpat** [comment]
Bart popped in on my stream; if you run the `.love` as a fused game, or you fuse it to the .exe, the save directory changes to `~/.local/share/<identity>/`.

**Comment by Rami-Sabbagh** [comment]
yeah, no way to fix that, chose one, builds or the git ripo, or run with -fused

**Comment by Rami-Sabbagh** [comment]
wait, you showcased liko12 in your stream ? Sweet @josefnpat

**Comment by josefnpat** [comment]
haha, I guess so :) The pioc8 guys have been fighting about pico8 vs pv8 vs TIC, so I started fighting for liko12, haha.

**Comment by Rami-Sabbagh** [comment]
:)
