### ISSUE TITLE
Missing font characters

### ISSUE THREAD

**Issue by chimmihc1** [LIKO-12/LIKO-12#60]
The font seems to be missing a few characters.

* ```$```
   * String patterns.
* ```\```
    * Part of the Lua syntax.
* ```|```
* ```@```
* ```&```

**Comment by mseyne** [comment]
Why not use the TIC computer font : 
TIC computer 6x6 font.zip from https://nesbox.itch.io/tic
It is released under creative common public domain.

I feel it is more readable (for example, the g is aligned)

**Comment by Rami-Sabbagh** [comment]
Our font is 5x3 ..., But I'm thinking of adding custom font support in v0.6

**Comment by Rami-Sabbagh** [comment]
also those chars do exists in my font, but had something wronge in my feltering format

**Comment by Rami-Sabbagh** [comment]
Fixed in LIKO12 V0.6, The chars were messing from the font image ( I wish you understand them )
