### ISSUE TITLE
copy-paste text in editor

### ISSUE THREAD

**Issue by mseyne** [LIKO-12/LIKO-12#62]
One feature I like from pico is to be able to select, copy and paste the code.

I could try to implement it and contribute, as I learn to use liko.

Is it : love.system.getClipboardText and love.system.setClipboardText ?

**Comment by mseyne** [comment]
I guess, before to add copy-paste, I have to figure out how to select the text first. 😄

**Comment by Rami-Sabbagh** [comment]
yup, but the problem is: liko12 0.6 api has changed (minor changes for
final programmer), and the os is being rewritten, so, better leave that for
me :)

**Comment by Rami-Sabbagh** [comment]
also, there is api.setclip() and api.getclip().
about lk12 v0.6, don't worry about the api changes, as I said the apis are close together, and I will do a complete upgrade for games published at löve forums topic

**Comment by mseyne** [comment]
Ok, is it also possible to add the key TAB, doing nothing else than one space, but I am used to code with it ?

**Comment by Rami-Sabbagh** [comment]
I experienced that too

**Comment by mseyne** [comment]
I am actually converting the game tutorial I made for the future magazine, instead to use Pico, I will use Liko. Can I send you the code later for you to see if it is working with 0.6 ?

**Comment by Rami-Sabbagh** [comment]
This has been solved in PRE_04 which will be released soon !
