### ISSUE TITLE
Default screen resolution for LIKO future

### ISSUE THREAD

**Issue by mseyne** [LIKO-12/LIKO-12#64]
Hello Rami, 

Have you seen the specs of CraftOS 2.0 ? (https://docs.google.com/document/d/1SPNG-buIVE4bz9qp1cZfRc3BqI9m4mUvoQ3MOgCYf3o/edit)

As I see you move from console to a complete 8 bit fantasy computer (with all programs as files than can be modified), I believe it would be great to have by default a resolution of 320x200. It is the most common resolution of the 8 bit computer (like the famous commodore 64 and the games on Dos) and give a wide range of possibilities for games but also to build graphic user interface and other programs like it was done on computercraft. (keeping the 16 colors limitation and be able to change them like on the TIC computer would be awesome)

If liko can be this mix between pico for games and craftos for modularity, that is a gold project for me and I will contribute as much as I can.

Also, maybe it will not need to see the program packaged as cartridge in the future but maybe as disk ?
Sharing the files as program.disk (contening code, sprite, sound, etc..) and as png : program.disk.png

What do you think about it?

**Comment by Rami-Sabbagh** [comment]
192x128 being the default gives support for small screens, so it would be good to run on a tft screen. Setting it to 320x200 drops support for smaller screens + the cartos will have some support for handling bigger resolutions. If you looked at the WIP branch, you can change the res by editing /BIOS/bconf.lua
and applying this:
```lua
--Create a new gpu mounted as "GPU"
assert(P("GPU","GPU",{
  _ClearOnRender = true,
  _LIKO_W = 320,
  _LIKO_H = 200
}))
```

**Comment by Rami-Sabbagh** [comment]
Sorry, but I won't change the default resolution
