### ISSUE TITLE
Difficulty Printing Text

### ISSUE THREAD

**Issue by ZombieShock** [LIKO-12/LIKO-12#65]
My understanding that the Lua commmand 

print("whatever I was trying to print")

should work? Am I doing something terribly wrong here?

**Comment by Rami-Sabbagh** [comment]
yes, you must specify the x & y of the print:
```lua
function _init()
   color(8) --White
   print("Hello",15,15)
end
```

**Comment by ZombieShock** [comment]
Thanks a ton,  I realize this is one of the least urgent "issue" posts and doesn't pertain to your program as much as my incompetence with Lua. Good luck, experimenting with Liko-12 has me very excited about future updates.
