### ISSUE TITLE
Couldn't run it!

### ISSUE THREAD

**Issue by nejdetckenobi** [LIKO-12/LIKO-12#66]
I installed both `liblove0_0.10.2ppa1_amd64.deb` and `love_0.10.2ppa1_amd64.deb` to my system.
I can not see a `.love` file in your project!

Here's the project tree when I cloned:

```
.
├── api.lua
├── autorun.lua
├── class.lua
├── conf.lua
├── debugrun.lua
├── demos
│   ├── fire.lk12
│   ├── helloworld.lk12
│   ├── maze.lk12
│   ├── noise.lk12
│   ├── scale.lk12
│   ├── snake.lk12
│   ├── snakenew.lk12
│   └── tictactoe.lk12
├── editor
│   ├── code.lua
│   ├── console.lua
│   ├── init.lua
│   ├── sprite.lua
│   └── tile.lua
├── editorsheet.png
├── font.png
├── gif_1.gif
├── gif_2.gif
├── gif_3.gif
├── gif.lua
├── icon.ico
├── icon.png
├── libraries
│   ├── animation.lua
│   ├── basexx.lua
│   ├── colorize_lua.lua
│   ├── inspect.lua
│   ├── lume.lua
│   ├── map.lua
│   └── textbuffer.lua
├── LICENSE
├── liko-12.txt
├── main.lua
├── offsets
│   ├── android.lua
│   ├── desktop.lua
│   └── init.lua
├── README.md
├── runtime.lua
├── screenshot_1.png
├── screenshot_2.png
├── screenshot_3.png
├── screenshot_4.png
├── screenshot_5.png
├── screenshot_6.png
├── terminal_commands.lua
└── terminal.lua
```

How to run? Please explain more in your documentation. That's very disappointing.

**Comment by Rami-Sabbagh** [comment]
Sorry for not explaining in the documentation, Love accepts 2 to run projects in linux:
1) running .love file: The .love file is available at the releases page of this repository.

2) running from cloned repo: by entering the repo directory that contains main.lua file, oppening the terminal and typing :
```
love .
```

**Comment by mseyne** [comment]
Hello Rami,
Maybe in the release of the 0.6 we could add executables with all the libs (windows/linux) to have liko as a strand-alone.
I could help later using this : https://love2d.org/wiki/Game_Distribution
See ya.

**Comment by Rami-Sabbagh** [comment]
I guess this got solved
