### ISSUE TITLE
[WIP] No backspace key?

### ISSUE THREAD

**Issue by mseyne** [LIKO-12/LIKO-12#67]
Seem it is not possible to delete code in the editor.
I will propose a fix, it is an opportunity for me to propose my first patch to the project 😄

**Comment by Rami-Sabbagh** [comment]
The code editor is still nothing...

**Comment by mseyne** [comment]
I propose a pr : #68 😄 
Do you have an idea where I could start to help you on the WIP branch that would not collide with where you are working now?

**Comment by Rami-Sabbagh** [comment]
Fixed this :3
