### ISSUE TITLE
Crash GPU

### ISSUE THREAD

**Issue by HomineLudens** [LIKO-12/LIKO-12#70]
Hi,
while testing some code I've encounter this strange error:
![immagine](https://cloud.githubusercontent.com/assets/1007007/23835947/6bc335ea-0770-11e7-9a99-835e8d441c76.png)

The cartridge here: [aaa.zip](https://github.com/RamiLego4Game/LIKO-12/files/836911/aaa.zip)

**Comment by Rami-Sabbagh** [comment]
Fixed
