### ISSUE TITLE
In windows , Wrong Drive C:/// as prefix

### ISSUE THREAD

**Issue by zaher** [LIKO-12/LIKO-12#73]
I used Windows 8.1
there is prefix for prompt like this 
C:///>
I think it should be just >

**Comment by joshgoebel** [comment]
This is intentional.  The BIOS starts with two drives, C and D.  The prompt is correct.  The drive is virtual.

**Comment by Rami-Sabbagh** [comment]
I did talk with zaher, he did main thay it must be made like unix systems (drives mounted as folders), But I'm really don't want to do that so...

**Comment by Rami-Sabbagh** [comment]
This issue will be sorted as low priority, and I may not apply what it wants

**Comment by joshgoebel** [comment]
I'd much prefer mounting to.  Are you open to contributions to change it?

I figured if you made it drives that you wanted it that way on purpose.
