### ISSUE TITLE
Use binary files for .lk12 format?

### ISSUE THREAD

**Issue by egordorichev** [LIKO-12/LIKO-12#74]
Current liko-12 cartridges are very big and not optimized.

**Comment by brunosxs** [comment]
I vote for the same png style of piko, which is basically metadata

**Comment by Rami-Sabbagh** [comment]
Well the format has been changed at V0.6, and you can compress it by doing 'save disk -c', also I will add save as bin option so it will get smaller because I can fit 2 pixels in 1 byte.

Yes .png saving will be added soon after I do complete cleanup

**Comment by Rami-Sabbagh** [comment]
PICO-8 png doesn't save using metadata, instead by using the first to bits of each color value, so every pixel can store 1 byte (character)

**Comment by egordorichev** [comment]
@RamiLego4Game, each pixel is represented by 3 bytes: r, g and b (optional a for rgba format). So then, each pixel in pico8 format represents 3 chars.

**Comment by Rami-Sabbagh** [comment]
@egordorichev PNG is RGBA , every value is 1 byte, and zep is using the first 2 bits of each byte (remember there is the cartridge picture) so 2*4 = 8 -> 1 byte per pixel

**Comment by pablomayobre** [comment]
Well you could use only transparent pixels, for example if your cartridge has borders you could only use those borders, and you would have 3 bytes for pixels (R, G and B) and A would always be 0. That is an alternative option...

Does `save disk -c` use lzip compression with `love.math.compress`?

**Comment by Rami-Sabbagh** [comment]
@Positive07 Yup `save disk -c`uses lzip compression with `love.math.compress`

**Comment by egordorichev** [comment]
You should have a look onto picolove. It implements both png and text format parsers. Very useful.

**Comment by Rami-Sabbagh** [comment]
I already have the png encoding working, it's just a matter of packing the data in binary

**Comment by Rami-Sabbagh** [comment]
The new release `V0.6.0_PRE-07` has implemented the binary format.
