### ISSUE TITLE
build is not compatible with version of Love (linux)

### ISSUE THREAD

**Issue by galopeian1** [LIKO-12/LIKO-12#77]
![liko12_issue](https://cloud.githubusercontent.com/assets/27159027/25992017/4c315db4-36d3-11e7-90d7-a3f71826cb86.png)

after running 
```
love .
```
in linux terminal (and yes I cloned the WIP repo)

**Comment by brunosxs** [comment]
can't reproduce this...

Edited as I was using an old repo...
It nevertheless, works fine
![captura de tela de 2017-05-12 10-20-05](https://cloud.githubusercontent.com/assets/1557903/25999760/be74416a-36fc-11e7-8bb5-17e28c0bb628.png)

Just to confirm: are you using the official builds from love2d.org? If not you should. Don't use the packages served from your distro's official repos 'cos they'd definetely be outdated.

Just for reference, I am using love2d 0.10.2

**Comment by Rami-Sabbagh** [comment]
You must use the official love 0.10.2 from the love2d ppa repository (check http://love2d.org), I'm pretty sure it's not my fault.

**Comment by galopeian1** [comment]
my bad! thank you

**Comment by galopeian1** [comment]
I got it working after i downloaded the correct version of Love, this is very cool btw :^)

**Comment by Rami-Sabbagh** [comment]
Thanks :)
