### ISSUE TITLE
Working on Raspberry Pi?

### ISSUE THREAD

**Issue by dglaude** [LIKO-12/LIKO-12#93]
Would be great if LIKO-12 could work on Raspberry Pi.
This would permit to create physical version of this fantasy computer.

I found this http://pilove.mitako.eu/ and newer Pi have some OpenGL support.

**Comment by Rami-Sabbagh** [comment]
LIKO-12 runs fine on the rpi, I have it running on my retropi.

**Comment by egordorichev** [comment]
Oh, that's awesome tool. It allows your game to run kind-of like OS... @RamiLego4Game, you should look more into that.

**Comment by Rami-Sabbagh** [comment]
I know about it a long time ago, But I don't have the internet to upload a
build of LIKO-12 with it

**Comment by Rami-Sabbagh** [comment]
Hey @dglaude , I just got LIKO-12 working on the latest full raspbian ! (It failed to work on retropie and PiLove)

How to run it ?

1. Download the 3 ARM deb files from http://love2d.org/
2. Install liblove0 then love and finally liblove-dbg (Maybe I have mistaken the order)
3. Download the LIKO-12_PRE_03_Universal.love file from either Github or itch.io
4. Double click the love file, or do `love LIKO-12_PRE_03_Universal.love`
5. Enjoy !

**Note:** If you have the opengl driver enabled then LIKO-12 may display a blank screen, so just do `sudo raspi-config` and disable it.

I have tested it on my Raspberry Pi 3 (Check screenshots on my twitter)

**Comment by dglaude** [comment]
I succeeded to install LÖVE and run LIKO-12, but it is rather slow.
I tested both on a Pi2 and a Pi3... Pi3 seems mandatory and this might exclude PiZero(W).

Do you have a feature to display the FPS (CPU usage, I know it was high, above 90%)?
I tested on Raspbian desktop, it did not seems to work in "Frame Buffer mode".

My feeling is that it will only be playable with GPU accelerated trick, maybe there are other version of LÖVE2D that would work better.
I hope that once your project get traction, more Pi expert or LÖVE on Pi expert will be able to unlock the power of this.

I don't know the best sequence for step 2 but here is what I did:
```
sudo dpkg -i liblove0_0.10.2ppa1_armhf.deb 
sudo dpkg -i liblove-dbg_0.10.2ppa1_armhf.deb 
sudo dpkg -i love_0.10.2ppa1_armhf.deb 

```

I also did the following, that may have help with the dependancy:
```
sudo apt-get install libluajit-5.1-2
sudo apt-get install libsdl2-2.0-0
sudo apt-get -f install

```

In doubt, I repeated those command in various order.

Regards.

**Comment by Rami-Sabbagh** [comment]
Well, I noticed the low fps, what can I do ?
There's a demo called ghostmark that displays the fps:
```
install_demos
cd Demos
load ghostmark
run
```

This was the FPS for me:

![liko-rpi](https://user-images.githubusercontent.com/6272475/28334961-7a1035c2-6c05-11e7-98f2-cfc0646375a3.png)

**Comment by dglaude** [comment]
Sorry, I have no solution for this problem.
A good Pi support would be great, but is it your priority?
I suggest you keep working on everything else...
Maybe keep an issue open so that whenever a Pi LÖVE/GPU expert see it he can dig into it.
It is likely related to LÖVE and other game have the same issue, maybe some solved it already.
