### ISSUE TITLE
Console text stays under the keyboard in Android

### ISSUE THREAD

**Issue by mindbound** [LIKO-12/LIKO-12#94]
Using the latest LIKO-12 Android release V0.6.0_PRE_03 on a Samsung Galaxy Tab A tablet (Android 6.0.1), I observe that, once the screen is full (e.g., after `help`), several bottom lines always stay hidden under the pop-up keyboard. Could you take a look at this?

P.S. As a side note (not sure if this merits a separate issue, since I perhaps simply don't know where to look), does the system font come in several sizes and, if so, how can I switch between them? TIA.

**Comment by Rami-Sabbagh** [comment]
Sorry for replaying late @mindbound ,
No, there isn't any other available fonts, sorry for that, the current 4x5 font is the best for LIKO-12 resolution.

The help lines problem: Try to hold your device in portrait so all the screen shows without being covered by the keyboard, + the help program has a smart feature, once it reaches the last line of the screen, it tells you to press `escape` to continue, or press `q` to quit.

How do this play on an Android device: Press `escape` to close the on-screen keyboard, then press it again to start scrolling again, if you want to quit: touch the screen so the keyboard shows again, and press `q`

**Comment by Rami-Sabbagh** [comment]
I'll close the issue, if the problem isn't solved yet then feel free to reopen the issue
