### ISSUE TITLE
Drive doesn't exist (+where are the files) V0.6.0 PRE3 on OSX

### ISSUE THREAD

**Issue by dglaude** [LIKO-12/LIKO-12#95]
If I type "drives" at the D:/> prompt I get:
> D:/> drives
> C - 1656282/26214400 Byte (6.31%)
> D - 62609/26214400 Byte (0.23%)

But I can not cd any of those drive:
> D:/> cd c:
>
> ERR: /drives/C//terminal.lua:103:
> Drive doesn't exists
> D:/> cd d:
>
> ERR: /drives/C//terminal.lua:103:
> Drive doesn't exists

I can create file (save) and directory (mkdir) and list them (dir/ls).

But I don't find my files on the Max OSX.

Is there a trick or a bug (for OSX port)?

**Comment by dglaude** [comment]
folder command let me found my files.
C and D directories exist.
D directory contain the file I created (save test) and the folder I created (mkdir x).
But I can not access C drive...
So to access the Demos, I copied them from C to D (from the finder).

Still I believe there is either a bug or a problem with my installation.

**Comment by trelemar** [comment]
Try "cd C:/" or "cd D:/" the drive letter is case sensitive.

**Comment by dglaude** [comment]
Silly me!
Thank you very much. @trelemar
Save my day on android too (but folder fail on android, maybe need another app for file browsing intent).

**Comment by Rami-Sabbagh** [comment]
Yeah, folder doesn't work in android
