### ISSUE TITLE
Unable to load LIKO-12.app on Mac (macOS Sierra)

### ISSUE THREAD

**Issue by Liquidream** [LIKO-12/LIKO-12#96]
Hi,
I suspect this is something to do with Mac and how it treats "untrusted" apps, but when I try to load the latest download (LIKO-12_V0.6.0_PRE_03_Mac.zip), I get the following error:

- **The application "LIKO-12.app" can't be opened.**

I've looked in my Security & Privacy settings and can't see anything else I can change to (I already have it set to allow apps from "App Store and identified developers".

Any ideas?

**Comment by Rami-Sabbagh** [comment]
I can guess because LIKO-12 is untrusted app, I'm not an identified developer, And I don't have a mac device to test on.

so it's better to install LÖVE from http://love2d.org/ (There's mac osx downloads), and use the LIKO-12_PRE_03_Universal.love file

**Comment by Liquidream** [comment]
Yup, that worked - thank you.

**Comment by LoganDark** [comment]
macOS Sierra **completely removed** this option, there are plenty of tutorials online to enable it though.
![Allow apps from  anywhere](https://user-images.githubusercontent.com/4723091/29744103-8fbdc39c-8a52-11e7-9e2f-86e8f33e7726.png)

**Comment by mar-sw** [comment]
If you can't allow apps from anywhere, you can click the **Open** option in contextual menu with Ctrl.

**Comment by LoganDark** [comment]
You can also right-click, lol.
