### ISSUE TITLE
Allow changing the color palette in the runtime.

### ISSUE THREAD

**Issue by Malmik** [LIKO-12/LIKO-12#99]
Hi. I am thinking about colours adiusting / editing options like in TIC - 80 or similiar. It would be nice to make sprites from more than 15 of them. 
P.S - Could you make black colour as not transparent also?

**Comment by Rami-Sabbagh** [comment]
There are some plans to allow editing the palette, but not when running your game.

You can make the black color not trasnparent by calling `palt(0,false)`, visit: http://liko-12.readthedocs.io/en/latest/GPU/palt/

**Comment by Malmik** [comment]
Thanks!

**Comment by Rami-Sabbagh** [comment]
Custom palettes support has been added in 6de12327e43cce90ef020fe32da75bc059e0f1f7, It will be available in PRE_06 :tada:
